
  - description: ""
    label: "Learn"
    name: "learn"
    sort: 112
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/learn.tpl"
    content: "/content/learn.yaml"
    fields:
      - name: "learn_page_name"
        label: "Learn Page Name"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "learn_content"
        label: "Learn Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Learn Articles"
    name: "learn_articles"
    sort: 115
    listed: true
    hasRoute: true
    showAsTable: true
    parent: "learn"
    view: "/views/learn_articles.tpl"
    content: "/content/learn_articles.yaml"
    fields:
      - name: "learn_articles_name"
        label: "Learn Articles Name"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "learn_featured_image"
        label: "Learn Featured Image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "learn_articles_content"
        label: "Learn Articles Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "learn_date"
        label: "Learn Date"
        description: ""
        datatype: "date"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true

  - description: ""
    label: "Blog"
    name: "blog"
    sort: 110
    listed: true
    hasRoute: true
    showAsTable: false
    parent: null
    view: "/views/blog.tpl"
    content: "/content/blog.yaml"
    fields:
      - name: "blog_page_name"
        label: "Blog Page Name"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "blog_content"
        label: "Blog Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
  - description: ""
    label: "Blog Posts"
    name: "blog_posts"
    sort: 114
    listed: true
    hasRoute: true
    showAsTable: true
    parent: "blog"
    view: "/views/blog_posts.tpl"
    content: "/content/blog_posts.yaml"
    fields:
      - name: "blog_posts_name"
        label: "Blog Posts Name"
        description: ""
        datatype: "text"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "blog_featured_image"
        label: "Blog Featured Image"
        description: ""
        datatype: "images"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "blog_posts_content"
        label: "Blog Posts Content"
        description: ""
        datatype: "wysiwyg_basic"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
      - name: "blog_date"
        label: "Blog Date"
        description: ""
        datatype: "date"
        sort: 10000
        required: false
        relationship: null
        settings:
          list: true
